export default function SiteFooter({ html }) {
  return html`
      <style>
        text-container {
          border-color: #ccc;
        }
      </style>
      <footer class='pbe6'>
        <site-container>
          <text-container class='mi-auto text-center border-solid border-bs1 pbs3'>
          <p class="text-1">
          JS Naked Day. This page was generated by <a href="https://enhance.dev/" class="underline">Enhance</a> (view it on <a href="https://github.com/macdonst/js-naked-day.org" class="underline">GitHub</a>).
          </p>
          </text-container>
        </site-container>
      </footer>
    `
}
